export const UPDATE_WEALTH_SLIDER_VALUE = 'UPDATE_WEALTH_SLIDER_VALUE';
export const UPDATE_MAP_CSS = 'UPDATE_MAP_CSS';
export const UPDATE_TOOLTIP_VISIBILITY = 'TOGGLE_TOOLTIP';
export const UPDATE_TOOLTIP_CONTENT = 'UPDATE_TOOLTIP_CONTENT';
export const UPDATE_TOOLTIP_POSITION = 'UPDATE_TOOLTIP_POSITION';
export const TOGGLE_PROGRESSIVE_COLOR_MODE = 'TOGGLE_PROGRESSIVE_COLOR_MODE';